### PR TITLE
Create 32-ob-domestic-payments-access.json

### PR DESCRIPTION
**Pull request by mariantiris**
**Issue**: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/140

**Functionality**: Implements the required components for domestic payments submission, domestic payments read details. Added detached signature validation processing for requests, and detached signature signing for response.

### CODE REVIEW

**Comment by BohoCode** [comment]
:-) Might want to squash all these commits!

**Review by BohoCode — CHANGES_REQUESTED** [review]
You can squash all these commits into one commit by using 
`git rebase -i HEAD~n` where n is the number of commits you will want to squash... 

I can walk through it with you if you would like?

**Comment by jorgesanchezperez** [comment]
Please add a description about the changes and the issue link.

**Review by jorgesanchezperez — CHANGES_REQUESTED** [review]
No description provided.
No issue link provided.

**Comment by mariantiris** [comment]
> No description provided. No issue link provided.

Added missing description and issue.

**Review by jorgesanchezperez — DISMISSED** [review]

**Review by jorgesanchezperez — APPROVED** [review]

**Review by BohoCode — APPROVED** [review]

**Pull request merged**
